#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'srv-example','console_scripts','srv_server'
__requires__ = 'srv-example'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('srv-example', 'console_scripts', 'srv_server')()
    )
